// Generated by CoffeeScript 1.4.0

exports.Greeter = (function() {

  function Greeter() {}

  Greeter.prototype.greet = function(name) {
    return console.log("Hello " + name);
  };

  return Greeter;

})();
